name: fitspark
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  icons_plus: ^5.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  http: ^0.13.6
  pedometer: ^4.1.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/photos/
    - assets/svgs/food-bag-svgrepo-com.svg
    - assets/svgs/food-dinner-svgrepo-com.svg
    - assets/svgs/food-svgrepo-com.svg
    - assets/svgs/food-restaurant-svgrepo-com.svg
    - assets/svgs/bean.svg
    - assets/svgs/fibre.svg
    - assets/svgs/oil.svg
    - assets/svgs/bean-svgrepo-com.svg
    - assets/svgs/reshot-icon-bot-M9KSVXJAY5.svg
    - assets/photos/bicep.jpg
    - assets/photos/pexels-suzyhazelwood-1510392.jpg

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
